/*
 * Swagger Sparqling WS
 * This server will expose an API to Sparqling front end to create new SPARQL queries with a combinations of point and click on the [GRAPHOLscape](https://github.com/obdasystems/grapholscape) graph.  Sparqling will be released as a standalone appication but also the server will embedded in [MWS](https://github.com/obdasystems/mws) and Sparqling will be integrated in [Monolith](https://www.monolith.obdasystems.com/).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: info@obdasystems.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.obdasystems.sparqling.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.obdasystems.sparqling.model.VarOrConstant;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import javax.validation.constraints.*;
import javax.validation.Valid;

/**
 * Function
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2022-04-15T09:25:55.884Z[GMT]")public class Function  implements Serializable  {
  /**
   * Gets or Sets name
   */
  public enum NameEnum {
    ADD("ADD"),
    
    SUBCTRACT("SUBCTRACT"),
    
    MULTIPLY("MULTIPLY"),
    
    DIVIDE("DIVIDE"),
    
    SUBSTR("SUBSTR"),
    
    UCASE("UCASE"),
    
    LCASE("LCASE"),
    
    CONTAINS("CONTAINS"),
    
    CONCAT("CONCAT"),
    
    ROUND("ROUND"),
    
    CEIL("CEIL"),
    
    FLOOR("FLOOR"),
    
    YEAR("YEAR"),
    
    MONTH("MONTH"),
    
    DAY("DAY"),
    
    HOURS("HOURS"),
    
    MINUTES("MINUTES"),
    
    SECONDS("SECONDS");

    private String value;

    NameEnum(String value) {
      this.value = value;
    }

    @Override
    @JsonValue
    public String toString() {
      return String.valueOf(value);
    }

    @JsonCreator
    public static NameEnum fromValue(String text) {
      for (NameEnum b : NameEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }
  }
  @JsonProperty("name")
  private NameEnum name = null;

  @JsonProperty("parameters")
  private List<VarOrConstant> parameters = null;

  public Function name(NameEnum name) {
    this.name = name;
    return this;
  }

  /**
   * Get name
   * @return name
   **/
  @JsonProperty("name")
  @Schema(description = "")
  public NameEnum getName() {
    return name;
  }

  public void setName(NameEnum name) {
    this.name = name;
  }

  public Function parameters(List<VarOrConstant> parameters) {
    this.parameters = parameters;
    return this;
  }

  public Function addParametersItem(VarOrConstant parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<VarOrConstant>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

  /**
   * Get parameters
   * @return parameters
   **/
  @JsonProperty("parameters")
  @Schema(description = "")
  @Valid
  public List<VarOrConstant> getParameters() {
    return parameters;
  }

  public void setParameters(List<VarOrConstant> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Function function = (Function) o;
    return Objects.equals(this.name, function.name) &&
        Objects.equals(this.parameters, function.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Function {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
